model: 'LFR_DZ_CSTR'

doe: 'examples/stenosed_tube/DOE.csv'

wd: 'examples/stenosed_tube'

input: 'examples/stenosed_tube/C_curves'

plots: ['pred_vs_gt']

plot_filenames: ['pred_vs_gt.png']

parameters:
- 'alpha'
- 'beta'

parameter_bounds:
- [0.01, 0.99]
- [0.01, 0.99]
